# Ref:
# https://qiita.com/sikkim/items/447b72e6ec45849058cd
# https://github.com/sikkimtemi/selenium
version: '3'
services:

  selenium-chrome:
    image: selenium/standalone-chrome
    restart: always
    container_name: 'selenium-chrome'
    ports:
        - "4444:4444"

  python:
    build: .
    image: lipo-d-point-ar
    restart: always
    container_name: 'python'
    depends_on:
      - selenium-chrome
    env_file: .env.production
    command: 'tail -f /dev/null'
    working_dir: '/home'
